/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /healthz` — liveness + best-effort readiness.
         * @description Returns 200 with a per-component status body. The body is always
         *     JSON so monitoring can distinguish "process up but DB unreachable"
         *     from "process down" without a separate readiness endpoint.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPatterns"];
        put?: never;
        post: operations["createPattern"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patterns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPattern"];
        put?: never;
        post?: never;
        delete: operations["deletePattern"];
        options?: never;
        head?: never;
        patch: operations["patchPattern"];
        trace?: never;
    };
    "/v1/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One distinct shape in a pattern, as a standalone SVG document. */
        Atom: {
            /**
             * @description Stable within one pattern; referenced by `Cell::atom_id`.
             * @example atom-0
             */
            id: string;
            /**
             * @description `<svg viewBox="0 0 W H">` holding one `<path class="layer-N">` per
             *     palette entry and an optional `<path class="contour">`. Paths are
             *     absolute cubic Béziers. Colour is deliberately *not* baked in — the
             *     client binds each class to a CSS custom property so recolouring never
             *     re-parses the SVG.
             */
            svg: string;
        };
        /** @description One placement of one atom within the lattice. */
        Cell: {
            /** @description Matches an `Atom::id` in the same pattern. */
            atom_id: string;
            /** @description Integer lattice coordinates, not pixels. */
            position: [
                number,
                number
            ];
            transform: components["schemas"]["Transform"];
        };
        /** @description An sRGB colour. */
        Color: {
            /** @example #99a361 */
            hex: string;
        };
        /**
         * @description Per-dependency state. `skipped_not_configured` means the process booted
         *     without that dependency wired, which is a supported local-dev posture, not
         *     a fault.
         */
        ComponentStatus: {
            /** @enum {string} */
            status: "ok";
        } | {
            /** @enum {string} */
            status: "skipped_not_configured";
        } | {
            error: string;
            /** @enum {string} */
            status: "failed";
        };
        Components: {
            db: components["schemas"]["ComponentStatus"];
            r2: components["schemas"]["ComponentStatus"];
        };
        /** @description How the atoms tile the plane. */
        Composition: {
            cells: components["schemas"]["Cell"][];
            lattice: components["schemas"]["Lattice"];
        };
        /** @description Tuning for the pass that recovers grout lines and glaze edges. */
        ContourParams: {
            /**
             * Format: int32
             * @description Dark regions thicker than this many pixels are treated as a real colour
             *     layer rather than an outline. Clamped to 1..=32.
             * @default 4
             * @example 4
             */
            max_thickness: number;
            /**
             * Format: float
             * @description Higher catches finer and lighter lines. Clamped to 0.0..=1.0.
             * @default 0.4000000059604645
             * @example 0.4
             */
            sensitivity: number;
        };
        /** @description Every non-2xx response from this API has this shape. */
        ErrorBody: {
            /**
             * @description Human-readable cause. Safe to surface; never contains secrets.
             * @example pattern 0c8f… not found
             */
            error: string;
        };
        HealthBody: {
            components: components["schemas"]["Components"];
            /**
             * @description `ok` or `degraded`.
             * @example ok
             */
            status: string;
        };
        JobCreated: {
            /**
             * Format: uuid
             * @description Poll `GET /v1/jobs/{id}`, then fetch the result. Cite this id when
             *     saving the pattern so the save records what settings produced it.
             */
            job_id: string;
        };
        /**
         * @description Optional knobs for `POST /v1/jobs`. Every field has a server default, so a
         *     client should send only what the user actually changed — that way a default
         *     changing server-side doesn't need a client release. Sending `contour: null`
         *     disables the contour pass; omitting it keeps the default pass enabled.
         */
        JobParams: {
            /**
             * @description Per-channel 1%–99% percentile stretch before quantisation.
             * @default false
             */
            auto_levels: boolean;
            /**
             * @default {
             *       "max_thickness": 4,
             *       "sensitivity": 0.4000000059604645
             *     }
             */
            contour: null | components["schemas"]["ContourParams"];
            /**
             * Format: float
             * @description Bilateral filter strength, 0.0 (off) to 1.0 (aggressive). Expands into
             *     kernel radius plus spatial and colour sigmas.
             * @default 0.30000001192092896
             * @example 0.3
             */
            denoise: number;
            /**
             * Format: int32
             * @description `null` or omitted → auto-detect via the SSE elbow on a downsampled
             *     buffer, and `quality.passes` will include `auto_layers`. A number uses
             *     exactly that many colour clusters, clamped to 2..=16.
             * @default null
             */
            layers: number | null;
            /**
             * Format: int32
             * @description Connected components smaller than this (in px²) are dropped during
             *     vectorisation.
             * @default 16
             * @example 16
             */
            min_region_px: number;
            /**
             * Format: int32
             * @description Longest edge the image is resized to before processing. Clamped to 256..=4096.
             * @default 1024
             * @example 1024
             */
            target_px: number;
        };
        /**
         * @description The four states a run moves through.
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "done" | "failed";
        /** @description The repeating unit's two basis vectors, in atom-space pixels. */
        Lattice: {
            basis_a: [
                number,
                number
            ];
            basis_b: [
                number,
                number
            ];
        };
        /** @description Body for `POST /v1/patterns`. */
        NewPattern: {
            /** Format: date-time */
            captured_at: string;
            family?: string;
            /** Format: double */
            geo_lat?: number | null;
            /** Format: double */
            geo_lng?: number | null;
            /**
             * Format: uuid
             * @description The job that produced `pipeline`. Optional and additive: when present
             *     the derivation inherits the run's params, pipeline version and image
             *     hash, which is what makes a saved pattern reproducible. When absent the
             *     pattern is still saved, with a derivation that honestly records nothing
             *     about how it was produced.
             */
            job_id?: string | null;
            kind?: string;
            /**
             * @description Effective colours keyed `layer-N` / `contour`. Stored as the default
             *     colourway's overrides, not as a second copy of the palette.
             * @example {
             *       "layer-0": "#99a361"
             *     }
             */
            layers: {
                [key: string]: string;
            };
            name: string;
            origin?: string;
            photo_key: string;
            pipeline: components["schemas"]["PipelineOutput"];
            place_name?: string | null;
            /** @description Where the photo came from: web | mobile | unknown. */
            source?: string;
        };
        /**
         * @description Mutable fields on `PATCH /v1/patterns/:id`. An omitted field is left
         *     unchanged; `place_name: null` explicitly clears it.
         */
        PatchPattern: {
            family?: string | null;
            layers?: {
                [key: string]: string;
            } | null;
            name?: string | null;
            /**
             * @description Lands on the pattern's capture, so it also changes for any sibling
             *     pattern extracted from the same photo.
             */
            place_name?: string | null;
        };
        /**
         * @description A pattern as the API serves it: the aggregate flattened back into the shape
         *     clients already consume, plus the provenance fields the new model can now
         *     answer (`origin`, `pipeline_version`, `params`).
         */
        Pattern: {
            /** Format: date-time */
            captured_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Display grouping in the library, e.g. "My Imports". */
            family: string;
            /** Format: double */
            geo_lat?: number | null;
            /** Format: double */
            geo_lng?: number | null;
            /** Format: uuid */
            id: string;
            /** @description `floor` or `border`. */
            kind: string;
            /**
             * @description Effective colours: the default colourway's overrides, keyed `layer-N`
             *     and `contour`.
             * @example {
             *       "contour": "#343d07",
             *       "layer-0": "#99a361"
             *     }
             */
            layers: {
                [key: string]: string;
            };
            name: string;
            /**
             * @description How the pattern came to be: `captured`, `authored`, `generated`,
             *     `remixed` or `imported`. Denormalised from the pattern's derivation so
             *     listing stays join-free.
             */
            origin: string;
            params?: null | components["schemas"]["JobParams"];
            /**
             * @description The capture behind this pattern. `null` for a pattern with no photo —
             *     authored in the editor, or generated. Nothing produces those yet.
             */
            photo_key?: string | null;
            pipeline: components["schemas"]["PipelineOutput"];
            /**
             * @description The pipeline version behind this pattern, from its derivation. `null`
             *     for patterns saved before runs were recorded; `v2-legacy` for rows
             *     migrated from the pre-split schema.
             */
            pipeline_version?: string | null;
            place_name?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        PatternResponse: components["schemas"]["Pattern"] & {
            /**
             * @description Time-limited URL that resolves to the original photo bytes in
             *     R2. Renewed on every fetch — clients shouldn't cache this.
             */
            photo_url?: string | null;
        };
        /** @description Everything the image pipeline extracted from one photo. */
        PipelineOutput: {
            /**
             * @description The distinct shapes in the pattern. One today; symmetry detection will
             *     produce several.
             */
            atoms: components["schemas"]["Atom"][];
            composition: components["schemas"]["Composition"];
            contour?: null | components["schemas"]["Color"];
            /**
             * @description Colour per layer, indexed by the `N` in an atom's `layer-N` class.
             *     Authoritative: the server may clamp or auto-pick the layer count, so
             *     this can differ in length from what the client asked for.
             */
            palette: components["schemas"]["Color"][];
            quality: components["schemas"]["Quality"];
        };
        /** @description Which optional passes actually ran, for surfacing in the UI. */
        Quality: {
            /**
             * @description Names of preprocess/quantize/contour passes that actually ran, in execution order.
             *     Future repair stats (glare_px, shadow_px, flatten_dB, ...) get added as additive fields
             *     only once the corresponding pass lands — don't pre-design fields with no producer.
             * @example [
             *       "bilateral",
             *       "contour",
             *       "auto_layers"
             *     ]
             */
            passes: string[];
        };
        StatusBody: {
            /** @description Present only when `status` is `failed`. */
            error?: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * @description What to do to the atom before placing it. Only `identity` is produced today;
         *     the rotate and reflect variants exist for symmetry detection.
         */
        Transform: {
            /** @enum {string} */
            kind: "identity";
        } | {
            /** Format: float */
            degrees: number;
            /** @enum {string} */
            kind: "rotate";
        } | {
            /** Format: float */
            axis_degrees: number;
            /** @enum {string} */
            kind: "reflect";
        };
        UploadRequest: {
            /**
             * @description Client-declared content-type. Used to:
             *       1. Pick the file extension on the R2 key.
             *       2. Bind the same content-type into the presigned signature so
             *          the actual PUT can't smuggle a different mime.
             * @example image/jpeg
             */
            content_type: string;
        };
        UploadResponse: {
            /** Format: int64 */
            expires_in_seconds: number;
            /**
             * @description Reference this in `POST /v1/patterns` after the PUT succeeds.
             * @example photos/1f89aab7-8987-4a66-984b-cb3c4e4616bb.jpg
             */
            photo_key: string;
            /** @description PUT the raw bytes here with the same `Content-Type` that was requested. */
            presigned_put_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Always 200 so naive uptime checks don't flap; read `status` and `components` to tell a healthy process from a degraded one */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBody"];
                };
            };
        };
    };
    submitJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `image` is the photo bytes. `params` is an optional JSON blob of `JobParams`; send only the fields the user changed so server defaults survive. */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The photo. JPEG, PNG or HEIC.
                     */
                    image: string;
                    params?: null | components["schemas"]["JobParams"];
                };
            };
        };
        responses: {
            /** @description Accepted; the pipeline runs off the request path */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Missing image field, or unparseable params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id from POST /v1/jobs */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state of the run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusBody"];
                };
            };
            /** @description Unknown job. The store is in-memory, so a restart forgets it */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getJobResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id from POST /v1/jobs */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The extracted pattern */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineOutput"];
                };
            };
            /** @description Unknown job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Still queued or running; poll the status endpoint */
            425: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The run failed; the body carries the cause */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listPatterns: {
        parameters: {
            query?: {
                /** @description Clamped to 1..=1000. Defaults to 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The collection, newest capture first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternResponse"][];
                };
            };
            /** @description No database configured on this instance */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    createPattern: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPattern"];
            };
        };
        responses: {
            /** @description Saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternResponse"];
                };
            };
            /** @description Empty name or photo_key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No database configured on this instance */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getPattern: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pattern id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternResponse"];
                };
            };
            /** @description No such pattern */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No database configured on this instance */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    deletePattern: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pattern id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. The capture goes too unless another pattern still derives from it */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No database configured on this instance */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    patchPattern: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pattern id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPattern"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternResponse"];
                };
            };
            /** @description No such pattern */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No database configured on this instance */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            /** @description A presigned PUT the client uploads to directly */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Unsupported content type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Object storage is not configured on this instance */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
